### ISSUE TITLE
"News and announcements" ordered in time

### ISSUE THREAD

**Issue by eduardo-rodrigues** [SWIFT-HEP/swift-hep.github.io#21]
Seen on the homepage - right now the latest event comes 2nd, not first, but then the 3rd and 4th are OK.

**Comment by eduardo-rodrigues** [comment]
Hi @kreczko and @davidecostanzo, feel free to close if you prefer as-is.

**Comment by kreczko** [comment]
The order is
Aug 19, 2022 [New job opportunity in SWIFT-HEP (analysis) - deadline 14th Sep 2022](https://swift.hep.ac.uk/posts/2022-08-19-wp5-job-advert/)
Feb 1, 2022 [The simulation Opticks team to participate in the UK Hackathon 2022](https://swift.hep.ac.uk/posts/2022-02-01-gpuhackathon/)
Nov 2, 2021 [SWIFT-HEP workshop on 23-24 March 2022](https://swift.hep.ac.uk/posts/2021-12-03-third-workshop/)
Nov 2, 2021 [SWIFT-HEP workshop on 2-3 November 2021](https://swift.hep.ac.uk/posts/2021-11-02-second-workshop/)
Apr 1, 2021 [SWIFT-HEP starts!](https://swift.hep.ac.uk/posts/2021-04-01-start-of-swifthep/)

Is that wrong? Or has it been silently fixed since?

**Comment by eduardo-rodrigues** [comment]
That's clearly correct. It must have been fixed somehow, at some point, as I doubt my eyes got it wrong when I posted the issue. Never mind :-). Closing.
